compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

pnpMode: strict

defaultSemverRangePrefix: ''

supportedArchitectures:
    os:
        - current
        - darwin
        - linux
        - win32
    cpu:
        - current
        - x64
        - ia32
        - arm64
        - x86
    libc:
        - current
        - glibc
        - musl

enableTelemetry: false

nmSelfReferences: false

npmPublishAccess: restricted

progressBarStyle: 'patrick'

# MAKE YARN FAIL IF PEER DEPENDENCIES ARE NOT MET
logFilters:
    - code: YN0002
      level: error
